# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  NetTel:
    image: nettel
    depends_on:
      - otel-collector
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5131:5131
    environment:
      ASPNETCORE_ENVIRONMENT: Development,
      Otel__MetricEndpoint: http://otel-collector:4317,
      Otel__TracingEndpoint: http://otel-collector:4317,
      Otel__LogEndpoint: http://otel-collector:4317
    networks:
      - monitoring
  otel-collector:
    # image: otel/opentelemetry-collector:0.95.0
    image: otel/opentelemetry-collector-contrib:0.99.0
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./config/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
      - "4317:4317"
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    networks:
      - monitoring
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    depends_on:
      - jaeger
      - prometheus
      - otel-collector
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - monitoring
  # node_exporter:
  #   image: quay.io/prometheus/node-exporter:v1.5.0
  #   container_name: node_exporter
  #   command: '--path.rootfs=/host'
  #   pid: host
  #   restart: unless-stopped
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   networks:
  #     - monitoring
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775"
      - "6831:6831"
      - "6832:6832"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
      # - 13134:13133
      # - 4318:4317

    networks:
      - monitoring
