# cmd:  docker-compose up -d
# cmd:  docker-compose down
networks:
  monitoring:
    external: true

services:
  NetTel:
    image: nettel
    container_name: nettel
    # depends_on:
    #   - otel-collector
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5131:5131
    environment:
      ASPNETCORE_ENVIRONMENT: Development,
      Otpl__Endpoint: http://otel-collector:4317
    networks:
      - monitoring