# build cmd: sudo docker-compose -f docker-compose.yml build --no-cache
# start cmd: sudo docker-compose -f docker-compose.yml up -d
# stop cmd: sudo docker-compose -f docker-compose.yml down
# restart cmd: sudo docker-compose -f docker-compose.yml down && sudo docker-compose -f docker-compose.yml build --no-cache && sudo docker-compose -f docker-compose.yml up -d
networks:
  monitoring:
    external: true

services:
  NetTel:
    image: nettel
    container_name: nettel
    # depends_on:
    #   - otel-collector
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5131:5131
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      UserTel__Endpoint: http://UserTel:5035
      Otpl__Endpoint: http://otel-collector:4317
    networks:
      - monitoring
 
  UserTel:
    image: usertel
    container_name: usertel
    # depends_on:
    #   - otel-collector
    build:
      context: ../UserTel
      dockerfile: Dockerfile
    ports:
      - 5035:5035
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Otpl__Endpoint: http://otel-collector:4317
    networks:
      - monitoring
    