receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:
        endpoint: otel-collector:4318

exporters:
  prometheus:
    endpoint: otel-collector:8889

  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  logging:
    verbosity: detailed
    
processors:
  batch:
    timeout: 1s

extensions:
  health_check:
    endpoint: otel-collector:13133

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      # exporters: [logging, prometheus]
      exporters: [prometheus]

    traces:
      receivers: [otlp]
      processors: [batch]
      # exporters: [logging, otlp/jaeger]
      exporters: [otlp/jaeger]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]